version: '3.4'
services:
  server:
    container_name: server
    restart: always
    environment:
      PORT: 3000
      REDIS_PORT: 6379
      REDIS_HOST: redis
    build:
      context: ./server
      dockerfile: dockerfile        
    ports:
      - 3000:3000
    volumes:
      - db:/home/node/app/data
  
volumes:
  db:
