openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API

servers:
  - url: http://{base_url}/{env_id}
    variables:
      base_url:
        default: localhost:3000
        description: server
      env_id:
        default: v1
        description: path selector

paths:
  /ping:
    get:
      description: |
        ping then pong!
      operationId: ping
      x-exegesis-controller: ping
      responses:
        "200":
          description: OK

  /pet:
    post:
      description: post pet
      operationId: postPet
      x-exegesis-controller: pet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                fav_number:
                  type: integer
              required:
                - name
      responses:
        "200":
          description: OK
